# Generated by Django 4.2.11 on 2026-09-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acta',
            name='confidence_score',
            field=models.FloatField(blank=True, db_index=True, default=None, help_text='Nivel de confianza consolidado (0.0-1.0). 0.7*transcription + 0.3*avg campo. <0.70 entra a revisión humana.', null=True),
        ),
        migrations.AlterField(
            model_name='aiprovidersettings',
            name='model',
            field=models.CharField(help_text='Slug oficial del modelo. Use dropdown o valores exactos (ej: deepseek-flash / gemini-3.6-flash).', max_length=120),
        ),
    ]
