# Generated by Django 4.2.11 on 2026-09-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_confidence_score_acta'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicalorganization',
            name='logo_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='org_logos/'),
        ),
    ]
