# Generated by Django 4.2.11 on 2026-09-18 07:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_politicalorganization_logo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_concurrent', models.PositiveSmallIntegerField(default=2, help_text='Número máximo de actas procesando en paralelo en Celery. Limitado a 4 para no saturar el VPS.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('auto_batch_enabled', models.BooleanField(default=False, help_text='Si está activado, el sistema automáticamente encola lotes pendientes sin presionar Procesar Lote.')),
                ('auto_batch_interval_secs', models.PositiveIntegerField(default=30, help_text='Cada cuántos segundos verifica nuevos lotes pendientes para auto-procesar.', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(600)])),
                ('poll_progress_interval_secs', models.PositiveSmallIntegerField(default=3, help_text='Intervalo de actualización en UI (HTMX poll) para progreso en tiempo real.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)])),
                ('max_batch_size_per_dispatch', models.PositiveSmallIntegerField(default=8, help_text='Máximo número de actas encoladas por cada Procesar Lote / auto-dispatch.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('per_acta_timeout_secs', models.PositiveSmallIntegerField(default=90, help_text='Timeout máximo (segundos) por acta individual en Celery worker (hard-kill beyond).', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(180)])),
                ('retry_count_job', models.PositiveSmallIntegerField(default=2, help_text='Reintentos automáticos si falla el job de Celery antes de marcarlo como error.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('retry_backoff_secs', models.PositiveSmallIntegerField(default=45, help_text='Base para backoff exponencial entre reintentos (segundos).', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(600)])),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Procesamiento Batch',
                'verbose_name_plural': 'Configuraciones de Procesamiento Batch',
                'db_table': 'vps_processing_config',
            },
        ),
    ]
